[project]
name = "mmx"
version = "0.1.0"
description = "Multimedia metadata tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pyperf>=2.9.0",
    "pytest>=8.4.1",
]
